### ISSUE TITLE
CCSDS command length > expected in MDB

### ISSUE THREAD

**Issue by dhosa** [yamcs/yamcs#105]
Here is the Hex dump of a command without any argument 
[18 02 c0 bb 00 29 42 c7 a3 86 9c 29 00 00 00 1f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 5b 7b ]

which is too long, compared to the 128-bit definition of CCSDS header.

**Comment by bitblit11** [comment]
I see this issue is still open.  YAMCS defaults the command minimum size to 48 bytes.  You should be able to override it but see issue 141 at https://github.com/yamcs/yamcs/issues/141 .  The configuration parameter isn't parsed correctly.  Also, be aware that the checksum always goes in the last 2 bytes of the message.  If you use all 48 bytes, the last two bytes of your data will get stepped on.
