### ISSUE TITLE
[Feature] History of Streams/parameters

### ISSUE THREAD

**Issue by xsmarty** [yamcs/yamcs#112]
As a client I would like to retrieve the history of a parameter/stream through websockets.

**Comment by fqqb** [comment]
We have functionality for this in our latest version. Not through websocket but through rest, since it's about a one-time request.

You can see http://www.yamcs.org/docs/api/REST_API/ for the details. There are several operations available, the one you should choose depends on your application. In summary there's support for

* Paged history access (every request reads in a fixed number of parameter values from a chosen offset)
* Full history downloads (if your application has a use for that, i'm guessing not)
* Sampled parameters. Here we split a defined range in different periods, to calculate an average value. This is especially useful as a datasource for plotting numeric values if you require support for that.

For generic table data (which your 'streams' refer to from knowing your project), there are low-level methods that give similar access directly to stored records.

* Page-per-page: http://www.yamcs.org/docs/api/List_Table_Data/
* Full history downloads: http://www.yamcs.org/docs/api/Download_Table_Data/

It's all very fresh, but has been performing well for our own needs.
