### ISSUE TITLE
wrong type of start, stop

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#305]
in doc we have https://www.yamcs.org/docs/http/Get_Tag/

![image](https://user-images.githubusercontent.com/432168/50895150-f17ad480-140d-11e9-9e56-86fd5a783931.png)

but really 

![image](https://user-images.githubusercontent.com/432168/50895257-3f8fd800-140e-11e9-90d3-d180a6620489.png)

must be int64

![image](https://user-images.githubusercontent.com/432168/50895361-93022600-140e-11e9-9131-22af1959e130.png)

**Comment by xpromache** [comment]
Looks to be originating from limitations in Javascript which uses doubles
for all the numbers:
https://github.com/protocolbuffers/protobuf/issues/2679
https://stackoverflow.com/questions/9643626/does-javascript-support-64-bit-integers

In this particular case we should export the timestamps in UTC strings
because those numbers are difficult to deal with from outside Yamcs.

**Comment by xpromache** [comment]
Somewhere in protobuf 3  a Timestamp type has been introduced (and is backward compatible with protobuf 2 which we are using):
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto

The protobuf to json conversion routine will convert this automatically to a string whereas the binary representation will do the normal protobuf conversion of the message. 

Therefore it looks like a good idea to start using this Timestamp type instead of manually converting the timestamp or sending two fields (one integer and one string) like we do now for example in parameter value class:
https://www.yamcs.org/docs/http/Get_Parameter_Value/
