### ISSUE TITLE
how to use unix time epoch

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#306]
I see in ParameterTypeProcessor.java 

![image](https://user-images.githubusercontent.com/432168/50987476-69cabe00-1512-11e9-82ab-073621c1a78b.png)

What I need to configure to use UNIX epoch time?

**Comment by xpromache** [comment]
sorry, where do you want to use the unix time epoch?

**Comment by vinnitu** [comment]
inside ccsds packet in secondary header

**Comment by Vitaliy136** [comment]
Hello! 
I am trying do the same.
I put unix time stamp in coarse-time in secondary header space packet.
I modified xls config like this
![image](https://user-images.githubusercontent.com/5146523/51602387-7508eb00-1f0f-11e9-9263-e79db227d463.png)
![image](https://user-images.githubusercontent.com/5146523/51602430-94a01380-1f0f-11e9-9732-22a6dee8f054.png)
Is it correct?
But seems calibration does not work because in yamcs-web i see shifted time (2029)

**Comment by xpromache** [comment]
Can you tell me where you see the shift (a screenshot would be appreciated)?

Do you have something in Calibration->calib2 column for the time_subsec?  (I cannot see it in the screenshot you provided, it kind of looks empty). That should contain the scaling factor (from whatever resolution to seconds).

**Comment by Vitaliy136** [comment]
I see time shift in yamcs-web for parameters

![image](https://user-images.githubusercontent.com/5146523/51619094-38051e80-1f38-11e9-8498-869e026653a5.png)

Scaling factor does not affect the coarse-time to make an offset for 10 years (as I understand it).
I generate time for packets in this way
dt = new Date()
coarse_time = floor(dt / 1000);
fine_time = floor(((dt % 1000) * 256 / 1000));

**Comment by xpromache** [comment]
The timestamp you see there is not the value of the parameter (computed according to the spreadsheet definition) but the timestamp associated. Currently the timestamp associated is coming from the so called PacketPreprocessor which if you didn't change our simulator configuration is the IssPacketPreprocessor which interprets always the timestamp as offset from GPS Epoch.

This timestamp is derived when the packet is injected into Yamcs, before the XTCE processing (i.e. the spreadsheet) which happens afterwards. This is a current limitation of Yamcs but it's difficult to overcome because we need that timestamp do archive the packet even without processing it.

Now, I can put an option on that IssPacketPreprocessor to interpret time differently but my question to you is: why do you use the IssPacketPreprocessor? Is there some need to be compatible with something? Where are your packets coming from actually?

**Comment by xpromache** [comment]
If you don't configure it, the default one IssPacketPreprocessor
<https://www.yamcs.org/yamcs/javadoc/index.html?org/yamcs/tctm/IssPacketPreprocessor.html>
is
used (this from the time when Yamcs was only used for ISS):
https://www.yamcs.org/docs/server/UDP_TM_Data_Link/

But can you tell me where your packets are coming from?

As I said, I propose one of the two:
1. add an option for the IssPacketPreprocessor
<https://www.yamcs.org/yamcs/javadoc/index.html?org/yamcs/tctm/IssPacketPreprocessor.html>
 to allow to use Unix time.
2. make another packet pre-processor that is very simple and has more
options (if we don't need to follow any CCSDS or other standards).

I prefer 2. because in ISS packets the time is supposed to be GPS so if we
have an option to change that time into UNIX we kind of violate the packet
definition.

nicolae

**Comment by Vitaliy136** [comment]
I created simple packets generator in node js for tests. Thank you

**Comment by xpromache** [comment]
ok, then please wait until Monday, I will commit a
GenericPacketPreprocessor that can work with Unix time.

I propose this structure:
packet size (16 bits) - the size of the packet data to follow in big endian
packet data

I will have an option to read a 4 bytes sequence number and a 8 byte
timestamp from a user defined offset.
The 8 bytes timestamp is millisec from 1970 (like java
System.currentTimeMillisec()).

Is that ok with you?
Do you need a checksum (normally not required if you only have ground
communications)?

nicolae

**Comment by xpromache** [comment]
Please have  a look here:
https://github.com/yamcs/yamcs/blob/master/yamcs-simulation/etc/yamcs.simulator.yaml
and search for tm2_realtime.

It should do what you wanted.

**Comment by vinnitu** [comment]
Ideally I see some GenericCcsdsPacketPreprocessor which has optional secondary header, optional checksum, optional type-id, optional packet-id, time stamp (one of described in ccsds recommendation) setting in instance yaml config file and setting epoch in xls. So if I need only 2 type space packets - I don't use type-id, packet-id at all (but apid from primary header as switch), etc.

**Comment by vinnitu** [comment]
Or such situation when packet doesn't have time stamp at all - can yamcs set system timestamp when receive data?

**Comment by xpromache** [comment]
Yes, that should be possible, I will put some more options on the
GenericPacketPreprocessor next weekend.
I think we don't need to care about the CCSDS header too much as long as
you can specify where to extract the necessary fields (sequence count,
timestamp) from.
