### ISSUE TITLE
Blank documentation pages

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs#383]
Some documentation pages are now empty.
https://yamcs.org/docs/yamcs-server-manual/mdb/command-definitions/
https://yamcs.org/docs/yamcs-server-manual/mdb/parameter-definitions/

**Comment by fqqb** [comment]
thanks for the report, they are placeholders introduced after a recent documentation restructuring.
I'll prepare new content in the coming days.

**Comment by AdamElliott-AB** [comment]
Thank you for the quick response. I thought I saw content there before, but perhaps I was mistaken.

**Comment by fqqb** [comment]
It could be you're referring to this content: https://yamcs.org/docs/yamcs-server-manual/mdb/loaders/sheet/

This details how to encode the mission database using a spreadsheet. It's the best documented option, because we've had this around for a long time.

But I think we should have some general MDB documentation - unattached to any of the input formats.
