### ISSUE TITLE
Is it possible to make web displays scrollable?

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [yamcs/yamcs#499]
Hello everyone,

I came across the following issue when rendering YAMCS studio display on YAMCS Webapp Displays utility:

![web display scrolling](https://user-images.githubusercontent.com/68551873/106196866-97c1e000-6177-11eb-942b-4f407f26c90a.png)

As you can see on the left on YAMCS Studio, I am able to scroll all the way down. However on the webapp, I'm not able to.

Any chance I'm missing something?

Or is this capability not added yet?

Thanks in advance
Lorenzo

**Comment by fqqb** [comment]
I agree this is undesirable. It's not going to be a quick-fix, because I want to bundle this work when visiting related topics like zoom-to-fit and zoom in/out. The interaction between the canvas draw logic and the wrapping HTML element is the complicated part here.

Current behaviour is that yamcs-web fits the available space, and then the displays crops to those dimensions.

**Comment by fqqb** [comment]
Scrollbars, and zoom in/out added on master.
