### ISSUE TITLE
WebApp Homepage Missing Info on Latest Build

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [yamcs/yamcs#537]
Hi there,

I just installed 2f6f9953bd00755a3324d435cf1544e7dffc84ac and when I start up YAMCS, I get the following:

![Screenshot from 2021-03-18 13-29-23](https://user-images.githubusercontent.com/68551873/111678496-5bf9dd00-87ee-11eb-95af-019eec679075.png)

As you can see, it only shows information about the CCSDS header(which is the very first row), but not the rest. It does show Parameter information when I go to the `Paramaters ` section of the sidebar, but it does not show the information on Home anymore on this build. If I build any older version of YAMCS(such as ac64eeb295ca20093c4a47e2156da0fc6e323adf) it works. It looks like the latest build might have done this.

Hope the issue makes sense.
Lorenzo

**Comment by xpromache** [comment]
Are you using container inheritance or composition? For the difference please read this: 
https://docs.yamcs.org/yamcs-server-manual/processors/tm-processing/

I did change the behavior because the old one was not correct. Now the packets which show on that page are only those inheriting from the container received via data link and passed on the stream (the one that is configured with the rootContainer property of the stream). 

If that container is decomposed (using container composition) in one ore more containers (covering partially the packet) then those will not appear.

The main reason I did that is because the binary packets are stored in the archive with that name, so it would be wrong to use the name of a container that covers only partially the packet to store the whole packet.

**Comment by lorenzo-gomez-windhover** [comment]
Unless I misunderstand the XTCE standard,  I'm pretty sure we use inheritance for our containers:

```
              <SequenceContainer name="AK8963_DIAG_TLM_MID">
                    <EntryList>
                        <ParameterRefEntry parameterRef="AK8963_DiagPacket_t"/>
                    </EntryList>
                    <BaseContainer containerRef="cfs-ccsds/cfs-tlm-hdr">
                        <RestrictionCriteria>
                            <ComparisonList>
                                <Comparison parameterRef="cfs-ccsds/ccsds-apid" value="275"/>
                            </ComparisonList>
                        </RestrictionCriteria>
                    </BaseContainer>
                </SequenceContainer>
```

However, as you can see we do use composition with ParameterRefEntry* types that are defined in the namespace/spacesystem. Is this the composition you are referring to?

**Comment by xpromache** [comment]
What I mean with composition is to have a ContainerRefEntry in the EntryList.

With your XTCE it appears that there is a bug in the code I changed, I will investigate.

**Comment by lorenzo-gomez-windhover** [comment]
Thanks so much for the brief response! Good to know :+1:

**Comment by xpromache** [comment]
Can you please verify it is fixed in the last push?

**Comment by lorenzo-gomez-windhover** [comment]
Works like a charm now on 2334e83406d27c9b760de2cb1d0ff48b090dc859. Thanks!
