### ISSUE TITLE
Fast arriving packets with calibrators cause web client to disconnect

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#691]
To reproduce:

1. Clone the Yamcs quickstart repository.
2. Edit src/main/yamcs/mdb/xtce.xml, inserting the EpsIo SpaceSystem from the attached file EpsIo.xml to the end of the file, just before the closing `</SpaceSystem>`. (Note: GitHub does not allow attaching a .xml file, so the file is called Epsio.xml.txt.)
3. Start Yamcs via `mvn yamcs:run`.
4. In the Yamcs web UI, navigate to Telemetry > Parameters > EpsIo.
5. Start the attached Python script send_epsio_packet.py (note: GitHub does not allow attaching a .py file, so the file is called send_epsio_packet.py.txt)
: `$ python3 send_epsio_packets.py`

Expected result: Telemetry is displayed in the Yamcs UI.

Actual result: Yamcs web UI says "Connection to Yamcs was lost." (See screen shot below.)

![image](https://user-images.githubusercontent.com/1649381/174659553-f8f9224a-e19a-4629-850d-8af2ea611d2f.png)

If you connect to Yamcs again by refreshing the browser and then start the Python script again, the connection will be lost again.

In the Yamcs log, there is an error shown:

~~~
11:20:58.068 _global [31] HttpRequestHandler 2a760b40 GET /api/mdb/myproject/parameters?system=/myproject/EpsIo&details=true&pos=0&limit=100 200
11:22:37.896 _global [28] WebSocketObserver [18] Skipping frame because channel is not writable
11:22:37.896 _global [28] WebSocketObserver [18] Too many (1) dropped messages. Forcing disconnect
11:22:37.897 _global [35] WebSocketFrameHandler Channel /0:0:0:0:0:0:0:1:51728 closed
~~~

## Attached files

Addition to the xtce.xml file:

[EpsIo.xml](https://github.com/yamcs/yamcs/files/8942933/EpsIo.xml.txt)

Python script exhibiting the bug:

[send_epsio_packets.py](https://github.com/yamcs/yamcs/files/8942934/send_epsio_packets.py.txt)

**Comment by xpromache** [comment]
The parameters subscribed on that page is updated with two messages one of 80KB and another one of 4KB.

By default the websocket uses 64KB high water mark:
https://docs.yamcs.org/yamcs-server-manual/services/global/http-server/

That means that after the 80KB message is sent, the high water mark will be exceeded and so the message of 4KB cannot be written and the socket will be closed.  

There are two threads involved in this:
 - first thread (created in the TM link) that receives data from the python script processes it and puts it into the Netty buffer
 - second thread (from Netty) which empties the buffer.

If the first thread runs fast enough to process two packets before the netty thread managed to empty the buffer then the problem appears.


We are implementing an option to drop data in these cases (only if the parameter has been subscribed with that specific option!). But in this case, the option will result in very often the 4KB data being dropped.

**It is better to increase the high water mark anyway in this case.**


Another longer-term discussion is why the data is so large.... It sickens me that an original TM packet of 200 bytes is blown up to 80KB of data.
That is because:
1. the aggregate values contain always the member names (we have an optimization done for non-aggregate parameters  which avoids sending the parameter name)
2. the json representation of the parameter values is extremely verbose.

Point 2. could be alleviated by using protobuf. A quick test with the python client shows that the 80KB messages are reduced to 24KB when protobuf is used instead of json.  Still seems a lot...
