### ISSUE TITLE
CFDP Service protocol standard

### ISSUE THREAD

**Issue by jiangha4** [yamcs/yamcs#780]
In the Java docs for the implementation of the CDFP service, it says that the service is implemented using protocol CCSDS 727.0-B-4. 

https://docs.yamcs.org/javadoc/yamcs/latest/org/yamcs/cfdp/CfdpService.html

Is there a possibility to update to CCSDS 727.0-B-5?

**Comment by loricvdt** [comment]
The latest additions were indeed done using the latest B-5 document but since our version does not implement all features of the specification anyway the definition of "adhering" to a certain version only makes a certain amount of sense. It is my understanding that the protocol is backwards compatible, so we will update the documentation to mention the newer document anyway.
If there are features of the B-5 version that is not present in yamcs and you wish to see, feel free to make a PR implementing it.
