### ISSUE TITLE
Large CFDP uplink causes high Yamcs CPU utilization until completion of the transfer

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#860]
To reproduce:

1. Configure Yamcs and the destination system to support CFDP.
2. In the Yamcs UI, request a CFDP uplink with a file around 10Mbyte in size, and start the transfer.

Expected result: Yamcs CPU utilization does not increase over time.

Actual result: Yamcs CPU utilization goes up over time until the transfer completes. In my test it goes up to over 300% load average before the transfer completes, while normal load for telemetry processing only on the same systems is about 15%.

Details:
- Uplink max PDU size is 93 bytes. (This is very small, but we are limited to a 128-byte uplink frame, and the frame header and other overhead necessitates this small PDU size.)
- sleepBetweenPDUs is 16ms. (Changing the delay to 50ms does not seem to change the behavior.)

**Comment by xpromache** [comment]
I finally spent a bit of time to debug this - it is caused by the command history. Each CFDP transfer adds an entry into the command history.

Each PDU sent out will cause an update of that entry (the "Sent" ack) but while the entries in the cmdhistory table  in the archive overwrite eachother, they are remembered into the CommandHistoryRequestManager and even more stupidly it makes a copy of all of them each time a new one is received:
https://github.com/yamcs/yamcs/blob/master/yamcs-core/src/main/java/org/yamcs/cmdhistory/CommandHistoryRequestManager.java#L169


In the context of the COP1 I was already considering introducing a counter for the Sent ack - to allow a command to be sent multiple times (the current behavior of providing the Sent ack only when acknowledged by COP1 has confused many people) 

The CFDP outgoing PDUs look like another good application of the Sent ack counter - so I think it's time to implement it.
