### ISSUE TITLE
ConcurrentModificationException is possible during CFDP options in DataFile class

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#895]
The DataFile class has an unsynchronized list "dataFileSegments" that can be read and modified by different threads. The particular problem we found was caused by a ConcurrentModificationException in getReceivedSize(). Apparently another thread added a segment using addSegment() at the same time.

The easiest fix I see is to make all accesses of "dataFileSegments" synchronized, probably by modifying the instantiation to use `Collections.synchronizedList(new ArrayList<>())`.

**Comment by merose** [comment]
Submited a PR: https://github.com/yamcs/yamcs/pull/896

**Comment by xpromache** [comment]
I set all methods as synchronized instead because adding a segment may involve multiple operations on that list (for example merging two segments when the gap between them is filled is two operations: 1. extend the first segment, 2. remove the second segment) and in that case the getReceivedSize may result in a size larger than the received size.
